[build]
  # Set to the folder that contains index.html. If your index.html is at the repo root, leave "."
  publish = "."

[build.processing]
  skip_processing = false

[build.processing.forms]
  enabled = true

[build.processing.html]
  pretty_urls = true
